# Generated by Django 4.1.7 on 2023-04-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_appuser_all_interests'),
        ('main_app', '0010_wish_delete_inter_alter_useractivity_activity'),
    ]

    operations = [
    ]
